/** Тип карточки редактора. */
export enum ECardType {
    CREATE_NEW_WORKOUT = 'CREATE_NEW_WORKOUT',
    EXERCISE_LIST = 'EXERCISE_LIST',
    CHOOSE_EXERCISE_TYPE = 'CHOOSE_EXERCISE_TYPE',
    CREATE_NEW_EXERCISE = 'CREATE_NEW_EXERCISE',
    REPETITIONS_LIST = 'REPETITIONS_LIST',
}

export enum EItemListType {
    SIMPLE = 'SIMPLE',
    TABLE_ROW = 'TABLE_ROW',
}
